# Generated by Django 5.0.1 on 2024-09-16 11:47

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comfort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='products/icons/%Y/%m/%d/')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('desc', models.TextField(max_length=1500)),
                ('country', models.CharField(max_length=256)),
                ('likes', models.CharField(blank=True, max_length=9)),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_type', models.PositiveSmallIntegerField(choices=[(1, 'Usz'), (2, 'Rub'), (3, 'Usd'), (4, 'Eur')])),
                ('max_humans', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.category')),
                ('comforts', models.ManyToManyField(blank=True, to='structure.comfort')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product/%Y/%m/%d/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.product')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime.today)])),
                ('to_date', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime.today)])),
                ('adult', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('child', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('baby', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('pet', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Want To Get'), (2, 'Confirmed'), (3, 'Canceled'), (4, 'Finished')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='structure.product')),
                ('renter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
